name: Pull Request Workflow
on:
  pull_request:
    branches:
      - master
jobs:
  test-suite-1:
    runs-on: ubuntu-latest
    steps:
      # Trigger the Test Suite 1 workflow
      - name: Trigger Test Suite 1
        uses: jakejarvis/gh-action-workflow-dispatch@v1
        with:
          workflow: 'Test Suite 1'
          token: ${{ secrets.PAT }}
  test-suite-2:
    runs-on: ubuntu-latest
    steps:
      # Trigger the Test Suite 2 workflow
      - name: Trigger Test Suite 2
        uses: jakejarvis/gh-action-workflow-dispatch@v1
        with:
          workflow: 'Test Suite 2'
          token: ${{ secrets.PAT }}
  merge-or-decline:
    needs: [test-suite-1, test-suite-2]
    runs-on: ubuntu-latest
    steps:
      # Check if both test suites passed
      - name: Check Test Results
        run: |
          if [ "${{ needs.test-suite-1.result }}" == "success" ] && [ "${{ needs.test-suite-2.result }}" == "success" ]; then
            echo "All tests passed. Merging pull request..."
            # Merge the pull request using the GitHub API
            curl -X PUT -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge"
          else
            echo "Tests failed. Declining pull request..."
            # Close the pull request using the GitHub API
            curl -X PATCH -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"state":"closed"}' \
            "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
          fi
