name: Test Suite 1
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Run tests for test suite 1
      - name: Run Test Suite 1
        run: echo "Running tests for test suite 1..."
